### ISSUE TITLE
Fix-It Issues

### ISSUE THREAD

**Issue by sl0wc0der** [Madhvik-P/CMPT785-BiBiFi#28]
For reference, the reports are available here: https://canvas.sfu.ca/courses/74693/pages/bibifi

Please raise a single Pull request for each issue and add the pull requests under this issue.

1. Allowing . and .. as filenames and usernames breaks the functionality. (G2 pg6, G6)
2. Allowing users with username / leads to system information leakage. (G2 pg8)
3. Using the first _ to detect the username doesn’t always work. If there are users with username 1 and 1_, user with 1_ will not be able to login. (G2 pg9)
4. Spaces at the end of the commands should be ignored. (G2 pg11)
5. Shared files are not getting updated. (G2 pg11)
6. Allows creation of . and .. directories breaks functionality. Going inside directory .. leaves the user unable to leave the directory. (G6 pg5)

**Comment by anant00729** [comment]
The Link to the Fixed Issues are as follows:

1. Share File Using mkfile command [#32](https://github.com/Madhvik-P/CMPT785-BiBiFi/issues/32)
2. Allowing . and .. as filenames and usernames breaks the functionality [#33](https://github.com/Madhvik-P/CMPT785-BiBiFi/issues/33)
3. Allowing users with username / leads to system information leakage. [#34](https://github.com/Madhvik-P/CMPT785-BiBiFi/issues/34)
4. Spaces at the end of the commands should be ignored. [#36](https://github.com/Madhvik-P/CMPT785-BiBiFi/issues/36)
5. Using the first _ to detect the username doesn’t always work. If there are users with username 1 and 1_, user with 1_ will not be able to login. [#37](https://github.com/Madhvik-P/CMPT785-BiBiFi/issues/37)
6. Allows creation of . and .. directories breaks functionality. Going inside directory .. leaves the user unable to leave the directory. [#38](https://github.com/Madhvik-P/CMPT785-BiBiFi/issues/38)
