### ISSUE TITLE
Allowing . and .. as filenames and usernames breaks the functionality

### ISSUE THREAD

**Issue by abhi10010** [Madhvik-P/CMPT785-BiBiFi#33]

**Comment by AnkIt1202** [comment]
![KS](https://user-images.githubusercontent.com/34647185/232265233-ab052980-3646-4578-95c3-90d843137403.jpeg)


PR of the fix: https://github.com/Madhvik-P/CMPT785-BiBiFi/pull/30

**Comment by abhi10010** [comment]
Looks good!
