### ISSUE TITLE
Allowing users with username / leads to system information leakage.

### ISSUE THREAD

**Issue by anant00729** [Madhvik-P/CMPT785-BiBiFi#34]
To Test:

1. login as admin
2. once logged in, type "adduser /" or "adduser foo/bar" or "adduser foo/" or "adduser /bar"

Check if says "Invalid Command".

**Comment by anant00729** [comment]
PR Link: https://github.com/Madhvik-P/CMPT785-BiBiFi/pull/35/files

**Comment by anant00729** [comment]
<img width="444" alt="Screen Shot 2023-04-15 at 1 07 16 PM" src="https://user-images.githubusercontent.com/20675885/232251126-3c76dba9-e19a-4ca3-84ff-8767886f9104.png">

**Comment by Madhvik-P** [comment]
Loos good to me.
