### ISSUE TITLE
Spaces at the end of the commands should be ignored.

### ISSUE THREAD

**Issue by anant00729** [Madhvik-P/CMPT785-BiBiFi#36]
To Test

1. login as any user and try following scenarios 

<img width="290" alt="Screen Shot 2023-04-15 at 1 13 32 PM" src="https://user-images.githubusercontent.com/20675885/232251365-ccb2a092-205e-499a-9ddc-8368bb00218e.png">

PR of the Fix: https://github.com/Madhvik-P/CMPT785-BiBiFi/pull/30

**Comment by Madhvik-P** [comment]
Tested and Looks good to me.
