### ISSUE TITLE
Using the first _ to detect the username doesn’t always work. If there are users with username 1 and 1_, user with 1_ will not be able to login. 

### ISSUE THREAD

**Issue by anant00729** [Madhvik-P/CMPT785-BiBiFi#37]
To test 

1. login as admin.
2. create two users "1" and "1_" using the following commands.

<img width="350" alt="Screen Shot 2023-04-15 at 1 22 27 PM" src="https://user-images.githubusercontent.com/20675885/232251769-6b1366e5-521c-4009-8caf-773be22b9534.png">

3. login as "1"

<img width="431" alt="Screen Shot 2023-04-15 at 1 22 52 PM" src="https://user-images.githubusercontent.com/20675885/232251779-d6af6700-dbfa-49cc-b3c2-af53ca523510.png">

4. login as "1_"

<img width="492" alt="Screen Shot 2023-04-15 at 1 23 07 PM" src="https://user-images.githubusercontent.com/20675885/232251786-b9dcbb5c-fe92-4e8d-baa2-f23102a207c0.png">

PR of the fix: https://github.com/Madhvik-P/CMPT785-BiBiFi/pull/30

**Comment by sh-ubh** [comment]
lgtm
